services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: FHaYH2q54Rn8DqPY
      POSTGRES_DB: fgc
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      args:
        - DATABASE_URL=postgresql://server:FHaYH2q54Rn8DqPY@db:5432/fgc?schema=public
    depends_on:
      - db
    restart: always
  client:
    build:
      context: ./client
      target: prod
    volumes:
      - /etc/letsencrypt/live/fgc.willma.me/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/fgc.willma.me/privkey.pem:/etc/nginx/ssl/privkey.pem
    restart: always
  reverse-proxy:
    image: nginx
    depends_on:
      - db
      - server
      - client
    volumes:
      - ./reverse_proxy/nginx.prod.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/fgc.willma.me/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/fgc.willma.me/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - "443:443"
    restart: always

volumes:
  db_data:
