services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: FHaYH2q54Rn8DqPY
      POSTGRES_DB: fgc
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    image: ghcr.io/willmadev/final_grade_calculator_server:${GIT_COMMIT_HASH:-latest}
    env_file: ./server/.env.prod
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.server.loadbalancer.server.port=8800"
      - "traefik.http.routers.server.rule=(Host(`fgc.willma.me`) && PathPrefix(`/api/`))"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"
    deploy:
      update_config:
        order: start-first
  client:
    image: ghcr.io/willmadev/final_grade_calculator_client:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
      - "traefik.http.routers.client.rule=Host(`fgc.willma.me`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
    deploy:
      update_config:
        order: start-first

  reverse-proxy:
    image: traefik
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=willmadev@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  letsencrypt:
