name: pipeline
on:
  push:
    branches:
      - "main"

permissions:
  packages: write

jobs:
  build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          tags: |
            ${{ ghcr.io/willmadev/final_grade_calculator_client }}:latest
            ${{ ghcr.io/willmadev/final_grade_calculator_client }}:${{ github.sha }}
  build-and-push-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        env:
          ENV_FILE: ${{ secrets.SERVER_ENV_PROD }}
        run: |
          echo "$ENV_FILE" > .env

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
          tags: |
            ${{ ghcr.io/willmadev/final_grade_calculator_server }}:latest
            ${{ ghcr.io/willmadev/final_grade_calculator_server }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-client
      - build-and-push-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create envfile
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: final_grade_calculator
          file: docker-stack.yml
          host: fgc.willma.me
          user: github_deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
